In [3]:
# numpy

# um objeto array multidimensional ndarray rápido e eficiente;
# funções para efetuar processamentos em todos os elementos de arrays ou operações matemáticas entre arrays;
# ferramentas para ler e gravar conjuntos de dados baseados em arrays em disco;
# operações de álgebra linear, transformadas de Fourier e geração de números aleatórios;
# uma API C madura para permitir que extensões Python e códigos C ou C++ nativos acessem as estruturas de dados e os recursos -
# de processamento da Numpy.

In [4]:
# importação
# Numpy foi projetado para ser eficaz em arrays de dados grandes invés do Pandas
import numpy as np

In [13]:
# teste de tempo

my_arr = np.arange(100000)
my_list = list(range(100000))

Wall time: 995 µs


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 42.9 ms


In [17]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 999 µs


In [18]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)

In [19]:
data

array([[ 0.16307609, -0.66733311,  0.44879542],
       [-0.54962657,  1.26727628, -0.85250202]])

In [21]:
# Operaçoes matemáticas com data
data * 10

array([[ 1.63076087, -6.67333113,  4.48795416],
       [-5.49626568, 12.67276277, -8.52502022]])

In [22]:
data + data

array([[ 0.32615217, -1.33466623,  0.89759083],
       [-1.09925314,  2.53455255, -1.70500404]])

In [23]:
# shape uma tupla que indica o tamanho de cada dimensão e dtype, que é um objeto que descreve o tipo de dado do array
data.shape

(2, 3)

In [24]:
data.dtype

dtype('float64')

In [25]:
# Criando ndarrays

In [26]:
# Aceita tipo de sequência e gera um novo array NumPY contendo os dados recebidos
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
# Sequências aninhadas serão convertidas em array multidimensional
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
# conferir as dimensões utilizando ndim ou shape
arr2.ndim

2

In [30]:
arr2.shape

(2, 4)

In [31]:
# metadados das arrays acima
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

In [33]:
# criando dados 0s ou de 1s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.empty((2, 3, 2)) # primeiro parâmetro especifica a quantidade de dimensões

array([[[1.27296994e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.42336543e-057]],

       [[5.58792341e-091, 4.27629921e-033],
        [1.53369141e-052, 5.40175432e-066],
        [6.48224660e+170, 4.93432906e+257]]])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
arr1 = [1, 2, 3, 4]
np.ones_like(arr1) # aceita um array e transforma em ones 

array([1, 1, 1, 1])

In [44]:
np.zeros_like(arr1) # aceita um array e transforma em zeros

array([0, 0, 0, 0])

In [51]:
np.eye(4) # matriz-identidade funciona também utilizando o np.identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
arr1 = [1, 2]

In [83]:
np.asarray(arr1) # converte a entrada para um ndarray

array([1, 2])

In [41]:
# arange versão embutida range do Python
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])