In [3]:
# numpy

# um objeto array multidimensional ndarray rápido e eficiente;
# funções para efetuar processamentos em todos os elementos de arrays ou operações matemáticas entre arrays;
# ferramentas para ler e gravar conjuntos de dados baseados em arrays em disco;
# operações de álgebra linear, transformadas de Fourier e geração de números aleatórios;
# uma API C madura para permitir que extensões Python e códigos C ou C++ nativos acessem as estruturas de dados e os recursos -
# de processamento da Numpy.

In [4]:
# importação
# Numpy foi projetado para ser eficaz em arrays de dados grandes invés do Pandas
import numpy as np

In [13]:
# teste de tempo

my_arr = np.arange(100000)
my_list = list(range(100000))

Wall time: 995 µs


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 42.9 ms


In [17]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 999 µs


In [18]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)

In [19]:
data

array([[ 0.16307609, -0.66733311,  0.44879542],
       [-0.54962657,  1.26727628, -0.85250202]])

In [21]:
# Operaçoes matemáticas com data
data * 10

array([[ 1.63076087, -6.67333113,  4.48795416],
       [-5.49626568, 12.67276277, -8.52502022]])

In [22]:
data + data

array([[ 0.32615217, -1.33466623,  0.89759083],
       [-1.09925314,  2.53455255, -1.70500404]])

In [23]:
# shape uma tupla que indica o tamanho de cada dimensão e dtype, que é um objeto que descreve o tipo de dado do array
data.shape

(2, 3)

In [24]:
data.dtype

dtype('float64')