In [3]:
# numpy

# um objeto array multidimensional ndarray rápido e eficiente;
# funções para efetuar processamentos em todos os elementos de arrays ou operações matemáticas entre arrays;
# ferramentas para ler e gravar conjuntos de dados baseados em arrays em disco;
# operações de álgebra linear, transformadas de Fourier e geração de números aleatórios;
# uma API C madura para permitir que extensões Python e códigos C ou C++ nativos acessem as estruturas de dados e os recursos -
# de processamento da Numpy.

In [2]:
# importação
# Numpy foi projetado para ser eficaz em arrays de dados grandes invés do Pandas
import numpy as np

In [13]:
# teste de tempo

my_arr = np.arange(100000)
my_list = list(range(100000))

Wall time: 995 µs


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 42.9 ms


In [17]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 999 µs


In [18]:
# Gera alguns dados aleatórios
data = np.random.randn(2, 3)

In [19]:
data

array([[ 0.16307609, -0.66733311,  0.44879542],
       [-0.54962657,  1.26727628, -0.85250202]])

In [21]:
# Operaçoes matemáticas com data
data * 10

array([[ 1.63076087, -6.67333113,  4.48795416],
       [-5.49626568, 12.67276277, -8.52502022]])

In [22]:
data + data

array([[ 0.32615217, -1.33466623,  0.89759083],
       [-1.09925314,  2.53455255, -1.70500404]])

In [23]:
# shape uma tupla que indica o tamanho de cada dimensão e dtype, que é um objeto que descreve o tipo de dado do array
data.shape

(2, 3)

In [24]:
data.dtype

dtype('float64')

In [25]:
# Criando ndarrays

In [26]:
# Aceita tipo de sequência e gera um novo array NumPY contendo os dados recebidos
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
# Sequências aninhadas serão convertidas em array multidimensional
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
# conferir as dimensões utilizando ndim ou shape
arr2.ndim

2

In [30]:
arr2.shape

(2, 4)

In [31]:
# metadados das arrays acima
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('int32')

In [33]:
# criando dados 0s ou de 1s
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.empty((2, 3, 2)) # primeiro parâmetro especifica a quantidade de dimensões

array([[[1.27296994e-311, 2.81617418e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.42336543e-057]],

       [[5.58792341e-091, 4.27629921e-033],
        [1.53369141e-052, 5.40175432e-066],
        [6.48224660e+170, 4.93432906e+257]]])

In [40]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
arr1 = [1, 2, 3, 4]
np.ones_like(arr1) # aceita um array e transforma em ones 

array([1, 1, 1, 1])

In [44]:
np.zeros_like(arr1) # aceita um array e transforma em zeros

array([0, 0, 0, 0])

In [51]:
np.eye(4) # matriz-identidade funciona também utilizando o np.identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
arr1 = [1, 2]

In [83]:
np.asarray(arr1) # converte a entrada para um ndarray

array([1, 2])

In [3]:
# arange versão embutida range do Python
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Tipos de dados para ndarrays

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [9]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [10]:
arr1

array([1., 2., 3.])

In [11]:
arr2

array([1, 2, 3])

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int32')

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [18]:
float_arr = arr.astype(np.float64) # objeto para transformar em um tipo de dado

In [16]:
float_arr

array([1., 2., 3., 4., 5.])

In [17]:
float_arr.dtype

dtype('float64')

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [22]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [23]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [24]:
# Utilizar o dtype de um para colocar no outro
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [25]:
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [26]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [29]:
empty_uint32 = np.empty(8, dtype='u4')

In [30]:
empty_uint32

array([       1,        1,        0,      551,     1104,        0,
       16777984,    32764], dtype=uint32)

In [31]:
# astype sempre cria um novo array (uma cópia dos dados), mesmo que o novo dtype seja igual ao dtype antigo.

In [37]:
np1 = np.array([-1.2, 2.3])

In [38]:
np1.astype(np.int32)

array([-1,  2])

In [39]:
np1

array([-1.2,  2.3])

In [1]:
# Aritmética com arrays NumPy

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [4]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [6]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [10]:
# Comparações
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [11]:
arr2 > arr # Comparação

array([[False,  True, False],
       [ True, False,  True]])

In [12]:
(arr2 > arr).dtype 

dtype('bool')

In [13]:
# Indexação básica e fatiamento

In [14]:
arr = np.arange(10)

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[5]

5

In [17]:
arr[5: 8]

array([5, 6, 7])

In [20]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [22]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [23]:
arr_slice[1]=12345 # Alteração que muda na arr original

In [24]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [25]:
arr_slice[:] = 64

In [26]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [27]:
# Para não modificar os dados utiliza-se .copy()
copy = arr_slice[:].copy()

In [32]:
copy[:] = 13

In [33]:
copy

array([13, 13, 13])

In [34]:
arr_slice # não modificou

array([64, 64, 64])

In [ ]:
arr2d = np.ar