In [1]:
# Importação da biblioteca Numpy
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr) # Numpy tem uma função para fazer a raiz quadrada de cada elemento

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
# os de cima são funções unárias (ufuncs unárias). Já os de baixo são ufuncs binárias porque aceitam dois arrays
# e devolve um unico array como resultado:

In [11]:
x = np.random.randn(8)
x

array([ 0.54813644, -0.75637393,  0.27070444, -2.13950814, -1.20072772,
        0.42495924, -1.59906608,  0.1998819 ])

In [13]:
y = np.random.randn(8)
y

array([-0.77666901, -1.30429365,  0.23913197, -1.96583334, -0.99377862,
        0.21218599, -0.88903544,  2.54554638])

In [15]:
np.maximum(x, y) # Comparação de dados e retorna o valor mais alto

array([ 0.54813644, -0.75637393,  0.27070444, -1.96583334, -0.99377862,
        0.42495924, -0.88903544,  2.54554638])

In [18]:
arr = np.random.randn(7) * 5
arr

array([-4.95618107, -7.12083626,  3.41192576,  5.90298891, -6.34723039,
       -4.21387001,  2.31229336])

In [19]:
np.modf(arr) # primeiro array é o restante do -4 Exemplo o segundo array é -4 porém tem um restante e esse restante foi
# atribuido para array de cima


(array([-0.95618107, -0.12083626,  0.41192576,  0.90298891, -0.34723039,
        -0.21387001,  0.31229336]),
 array([-4., -7.,  3.,  5., -6., -4.,  2.]))

In [24]:
remainder, whole_part = np.modf(arr)

In [26]:
remainder

array([-0.95618107, -0.12083626,  0.41192576,  0.90298891, -0.34723039,
       -0.21387001,  0.31229336])

In [27]:
whole_part

array([-4., -7.,  3.,  5., -6., -4.,  2.])

In [28]:
arr

array([-4.95618107, -7.12083626,  3.41192576,  5.90298891, -6.34723039,
       -4.21387001,  2.31229336])

In [29]:
np.sqrt(arr)

<ipython-input-29-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 1.84713989, 2.42960674,        nan,
              nan, 1.52062269])

In [33]:
np.sqrt(arr, arr) # in-place no array, segundo parametro muda o array

array([       nan,        nan, 1.35909525, 1.55871958,        nan,
              nan, 1.23313531])

In [32]:
arr # array mudado

array([       nan,        nan, 1.84713989, 2.42960674,        nan,
              nan, 1.52062269])

In [59]:
arr = np.array([ 0.64707499,  1.90668753,  1.26025681, -1.46437928,  0.93038936,
       -0.10606576,  1.08250269, -1.26550848,  0.41226027, -0.91618353])
arr

array([ 0.64707499,  1.90668753,  1.26025681, -1.46437928,  0.93038936,
       -0.10606576,  1.08250269, -1.26550848,  0.41226027, -0.91618353])

In [39]:
np.add(arr, 1) # recebe array e soma + 1
np.subtract(arr, 1) # recebe array e subtrai -1
np.multiply(arr, 1) # recebe array e multiplica
np.divide(arr, 1) # divide
np.power(arr, 3) # eleva e cuidado com o + 1

array([ 1.64707499,  2.90668753,  2.26025681, -0.46437928,  1.93038936,
        0.89393424,  2.08250269, -0.26550848,  1.41226027,  0.08381647])

In [61]:
np.fmax(arr, 1) # máximo de todos os elementos, se eles forem ponto fluante do segundo parametro aparecem

array([1.        , 1.90668753, 1.26025681, 1.        , 1.        ,
       1.        , 1.08250269, 1.        , 1.        , 1.        ])

In [60]:
np.fmin(arr, 1) # mínimo de todos os elementos, se eles estiverem abaixo ou seja ponto fluante eles aparecem

array([ 0.64707499,  1.        ,  1.        , -1.46437928,  0.93038936,
       -0.10606576,  1.        , -1.26550848,  0.41226027, -0.91618353])

In [64]:
np.mod(arr, 2) # módulo de todos os elementos 

array([0.64707499, 1.90668753, 1.26025681, 0.53562072, 0.93038936,
       1.89393424, 1.08250269, 0.73449152, 0.41226027, 1.08381647])

In [66]:
np.copysign(arr, 1) # apenas copia o sinal

array([0.64707499, 1.90668753, 1.26025681, 1.46437928, 0.93038936,
       0.10606576, 1.08250269, 1.26550848, 0.41226027, 0.91618353])